services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: mpk
      POSTGRES_PASSWORD: mpk
      POSTGRES_DB: mpk_harvester
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: